[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "napari-filaments"
dynamic = ["version"]
description = "Plugin for filament analysis"
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.10"
authors = [
    { name = "Hanjin Liu", email = "liuhanjin.sc@gmail.com" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: napari",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Testing",
]
dependencies = [
    "macro-kit",
    "magic-class>=0.7.6",
    "magicgui",
    "matplotlib",
    "numpy",
    "pandas",
    "psygnal",
    "scipy",
]

[project.optional-dependencies]
testing = [
    "napari",
    "pyqt5",
    "pytest",
    "pytest-cov",
    "pytest-qt",
    "roifile",
    "tox",
]
napari = [
    "napari",
]
himena = [
    "himena",
]

[project.entry-points."napari.manifest"]
napari-filaments = "napari_filaments:napari.yaml"

[project.urls]
"Bug Tracker" = "https://github.com/hanjinliu/napari-filaments/issues"
Documentation = "https://github.com/hanjinliu/napari-filaments#README.md"
Homepage = "https://github.com/hanjinliu/napari-filaments"
"Source Code" = "https://github.com/hanjinliu/napari-filaments"
"User Support" = "https://github.com/hanjinliu/napari-filaments/issues"

[tool.hatch.version]
path = "napari_filaments/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.pytest.ini_options]
testpaths = ["_tests"]
addopts = "-v"
filterwarnings = [
    "ignore::DeprecationWarning:qtpy",
    "ignore::DeprecationWarning:ipykernel",
    "ignore::DeprecationWarning:pkg_resources",
    "ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning",
    "ignore::DeprecationWarning:qtconsole",
    "ignore:distutils Version classes are deprecated",
    "ignore:path is deprecated:DeprecationWarning",
    "ignore:Jupyter is migrating its paths to use standard platformdirs:DeprecationWarning",
]
